const ArtistServer = [
  {
    id: "artist-1",
    name: "Atif Aslam",
    avatar: "/assets/artists/atif-aslam.jpeg",
    color: ["#783B43", "#422024", "#2F171A"],
    songs: [
      "song-1",
      "song-6",
      "song-8",
      "song-11",
      "song-13",
      "song-18",
      "song-21",
      "song-25",
      "song-28",
      "song-31",
    ],
    desc: "Lorem ipsum dolor sit amet consectetur",
  },
  {
    id: "artist-2",
    name: "Arijit Sing",
    avatar: "/assets/artists/arijit.jpeg",
    color: ["#CE232A", "#4D0F12", "#520F12"],
    songs: [
      "song-1",
      "song-5",
      "song-7",
      "song-9",
      "song-14",
      "song-19",
      "song-22",
      "song-25",
      "song-27",
      "song-29",
      "song-32",
    ],
    desc: "Lorem ipsum dolor sit amet consectetur",
  },
  {
    id: "artist-3",
    name: "Neha Kakkar",
    avatar: "/assets/artists/neha.jpg",
    color: ["#6603AB", "#26033F", "#220735"],
    songs: [
      "song-1",
      "song-6",
      "song-14",
      "song-17",
      "song-19",
      "song-21",
      "song-23",
      "song-26",
      "song-28",
      ,
    ],
    desc: "Lorem ipsum dolor sit amet consectetur",
  },
  {
    id: "artist-4",
    name: "Neeti Mohan",
    avatar: "/assets/artists/neeti-mohan.jpeg",
    color: ["#0E7FD3", "#06304E", "#082A43"],
    songs: [
      "song-2",
      "song-5",
      "song-8",
      "song-10",
      "song-15",
      "song-18",
      "song-20",
      "song-22",
      "song-26",
      "song-32",
    ],
    desc: "Lorem ipsum dolor sit amet consectetur",
  },
  {
    id: "artist-5",
    name: "Phalak Mucchal",
    avatar: "/assets/artists/phalak.jpeg",
    color: ["#E7329C", "#56143B", "#5B153E"],
    songs: [
      "song-2",
      "song-11",
      "song-14",
      "song-16",
      "song-20",
      "song-21",
      "song-24",
      "song-27",
      "song-29",
      "song-30",
    ],
    desc: "Lorem ipsum dolor sit amet consectetur",
  },
  {
    id: "artist-6",
    name: "Honey sing",
    avatar: "/assets/artists/honey.jpeg",
    color: ["#0E7FD3", "#06304E", "#082A43"],
    songs: [
      "song-2",
      "song-5",
      "song-6",
      "song-8",
      "song-9",
      "song-12",
      "song-15",
      "song-16",
      "song-17",
      "song-20",
      "song-22",
      "song-24",
      "song-26",
      "song-29",
      "song-30",
      "song-31",
    ],
    desc: "Lorem ipsum dolor sit amet consectetur",
  },
  {
    id: "artist-7",
    name: "Sonu Nigam",
    avatar: "/assets/artists/sonu.jpeg",
    color: ["#4370E1", "#192A54", "#182547"],
    songs: [
      "song-3",
      "song-7",
      "song-9",
      "song-10",
      "song-12",
      "song-16",
      "song-23",
      "song-25",
      "song-27",
      "song-30",
      "song-31",
      "song-32",
    ],
    desc: "Lorem ipsum dolor sit amet consectetur",
  },
  {
    id: "artist-8",
    name: "K K",
    avatar: "/assets/artists/kk.jpeg",
    color: ["#1C7EC3", "#0B304A", "#05243b"],
    songs: ["song-3", "song-15", , , , , , , , ,],
    desc: "Lorem ipsum dolor sit amet consectetur",
  },
  {
    id: "artist-9",
    name: "Muhit Chauhan",
    avatar: "/assets/artists/mohit.jpeg",
    color: ["#4370E1", "#192A54", "#182547"],
    songs: ["song-3", , , , , , , , , ,],
    desc: "Lorem ipsum dolor sit amet consectetur",
  },
  {
    id: "artist-10",
    name: "Monali Thakur",
    avatar: "/assets/artists/monali.jpeg",
    color: ["#CE232A", "#4D0F12", "#520F12"],
    songs: ["song-4", "song-17", , , , , , , , ,],
    desc: "Lorem ipsum dolor sit amet consectetur",
  },
  {
    id: "artist-11",
    name: "Tulsi Kumar",
    avatar: "/assets/artists/tulsi.jpg",
    color: ["#783B43", "#422024", "#2F171A"],
    songs: ["song-4", "song-7", "song-13", , , , , , , ,],
    desc: "Lorem ipsum dolor sit amet consectetur",
  },
];
export default ArtistServer;
