const PlaylistService = [
  {
    id: "playlist-1",
    title: "Peaceful piano",
    cover: "/assets/albums/album-1.jpeg",
    songs: ["song-1", "song-18", "song-20", "song-22", "song-24"],
    color: ["#440909", "#410606", "#270606"],
    desc: "Lorem ipsum dolor sit amet consectetur",
  },
  {
    id: "playlist-2",
    title: "Deep focus",
    cover: "/assets/albums/album-3.jpeg",
    songs: ["song-2", "song-9", "song-11", "song-13", "song-15"],
    color: ["#6F8FA6", "#29343C", "#262F35"],
    desc: "Lorem ipsum dolor sit amet consectetur",
  },
  {
    id: "playlist-3",
    title: "Chill lofi study",
    cover: "/assets/albums/1.jpeg",
    songs: [
      "song-1",
      "song-2",
      "song-3",
      "song-4",
      "song-5",
      "song-6",
      "song-7",
    ],
    color: ["#2B5A15", "#112109", "#12200B"],
    desc: "Lorem ipsum dolor sit amet consectetur",
  },
  {
    id: "playlist-4",
    title: "Focus flow",
    cover: "/assets/albums/3.jpg",
    songs: [
      "song-8",
      "song-9",
      "song-10",
      "song-11",
      "song-12",
      "song-13",
      "song-14",
    ],
    color: ["#6603AB", "#26033F", "#220735"],
    desc: "Lorem ipsum dolor sit amet consectetur",
  },
  {
    id: "playlist-5",
    title: "Todays top hit",
    cover: "/assets/albums/4.jpg",
    songs: ["song-15", "song-16", "song-17", "song-18", "song-19", "song-20"],
    color: ["#6F8FA6", "#29343C", "#262F35"],
    desc: "Lorem ipsum dolor sit amet consectetur",
  },
  {
    id: "playlist-6",
    title: "Rock classic",
    cover: "/assets/albums/5.png",
    songs: [
      "song-21",
      "song-22",
      "song-23",
      "song-24",
      "song-25",
      "song-26",
      "song-27",
    ],
    color: ["#CE232A", "#4D0F12", "#520F12"],
    desc: "Lorem ipsum dolor sit amet consectetur",
  },
  {
    id: "playlist-7",
    title: "Mood booster",
    cover: "/assets/albums/6.jpg",
    songs: ["song-28", "song-29", "song-30", "song-31", "song-32"],
    color: ["#CE232A", "#4D0F12", "#520F12"],
    desc: "Lorem ipsum dolor sit amet consectetur",
  },
  {
    id: "playlist-8",
    title: "Dark & stormy",
    cover: "/assets/albums/7.jpg",
    songs: ["song-1", "song-3", "song-5", "song-7"],
    color: ["#0E7FD3", "#06304E", "#082A43"],
    desc: "Lorem ipsum dolor sit amet consectetur",
  },
  {
    id: "playlist-9",
    title: "Valentine day",
    cover: "/assets/albums/8.jpg",
    songs: [
      "song-9",
      "song-11",
      "song-13",
      "song-15",
      "song-17",
      "song-19",
      "song-21",
    ],
    color: ["#783B43", "#422024", "#2F171A"],
    desc: "Lorem ipsum dolor sit amet consectetur",
  },
  {
    id: "playlist-10",
    title: "Bangladeshi Mix",
    cover: "/assets/albums/10.jpg",
    songs: ["song-23", "song-25", "song-27", "song-29", "song-31"],
    color: ["#0E7FD3", "#06304E", "#082A43"],
    desc: "Lorem ipsum dolor sit amet consectetur",
  },
  {
    id: "playlist-11",
    title: "Discover weekly",
    cover: "/assets/albums/11.jpg",
    songs: ["song-1", "song-2", "song-5", "song-8", "song-9", "song-10"],
    color: ["#4370E1", "#192A54", "#182547"],
    desc: "Lorem ipsum dolor sit amet consectetur",
  },
  {
    id: "playlist-12",
    title: "Black night music",
    cover: "/assets/albums/12.jpg",
    songs: [
      "song-2",
      "song-4",
      "song-6",
      "song-8",
      "song-10",
      "song-12",
      "song-14",
    ],
    color: ["#1C7EC3", "#0B304A", "#05243b"],
    desc: "Lorem ipsum dolor sit amet consectetur",
  },
  {
    id: "playlist-13",
    title: "Top artists",
    cover: "/assets/albums/13.jpg",
    songs: [
      "song-16",
      "song-18",
      "song-20",
      "song-22",
      "song-24",
      "song-26",
      "song-28",
    ],
    color: ["#E7329C", "#56143B", "#5B153E"],
    desc: "Lorem ipsum dolor sit amet consectetur",
  },
  {
    id: "playlist-14",
    title: "Desi hits",
    cover: "/assets/albums/10.webp",
    songs: ["song-30", "song-31", "song-32", "song-1", "song-5", "song-3"],
    color: ["#4370E1", "#192A54", "#182547"],
    desc: "Lorem ipsum dolor sit amet consectetur",
  },
];
export default PlaylistService;
