const GenreService = [
  //height = width = 194px
  {
    id: "genre-1",
    title: "Podcase",
    color: "#E13300",
    cover: "/assets/genres/genre-1.jpeg",
    playlists: ["playlist-1", "playlist-2"],
  },
  {
    id: "genre-2",
    title: "Made for you",
    color: "#1E3264",
    cover: "/assets/genres/genre-2.jpeg",
    playlists: ["playlist-1", "playlist-2"],
  },
  {
    id: "genre-3",
    title: "New Release",
    color: "#E8115B",
    cover: "/assets/genres/genre-3.jpg",
    playlists: ["playlist-1", "playlist-2"],
  },
  {
    id: "genre-4",
    title: "Desi",
    color: "#E13300",
    cover: "/assets/genres/genre-4.jpeg",
    playlists: ["playlist-1", "playlist-2"],
  },
  {
    id: "genre-5",
    title: "Hip Hop",
    color: "#121212",
    cover: "/assets/genres/genre-5.jpeg",
    playlists: ["playlist-1", "playlist-2"],
  },
  {
    id: "genre-6",
    title: "Rock",
    color: "#BC5900",
    cover: "/assets/genres/genre-6.jpeg",
    playlists: ["playlist-1", "playlist-2"],
  },
  {
    id: "genre-7",
    title: "",
    color: "#E91429",
    cover: "/assets/genres/genre-7.jpeg",
    playlists: ["playlist-1", "playlist-2"],
  },
  {
    id: "genre-8",
    title: "Life events",
    color: "#8D67AB",
    cover: "/assets/genres/genre-8.jpeg",
    playlists: ["playlist-1", "playlist-2"],
  },
  {
    id: "genre-9",
    title: "Latin",
    color: "#7358FF",
    cover: "/assets/genres/genre-9.jpeg",
    playlists: ["playlist-1", "playlist-2"],
  },
  {
    id: "genre-10",
    title: "Dance",
    color: "#E1118C",
    cover: "/assets/genres/genre-10.jpeg",
    playlists: ["playlist-1", "playlist-2"],
  },
  {
    id: "genre-11",
    title: "Mood",
    color: "#D84000",
    cover: "/assets/genres/genre-11.jpeg",
    playlists: ["playlist-1", "playlist-2"],
  },
  {
    id: "genre-12",
    title: "Discover",
    color: "#E1118C",
    cover: "/assets/genres/genre-12.jpg",
    playlists: ["playlist-1", "playlist-2"],
  },
  {
    id: "genre-13",
    title: "Workout",
    color: "#E91429",
    cover: "/assets/genres/genre-13.jpg",
    playlists: ["playlist-1", "playlist-2"],
  },
  {
    id: "genre-14",
    title: "R & B",
    color: "#1E3264",
    cover: "/assets/genres/genre-14.jpeg",
    playlists: ["playlist-1", "playlist-2"],
  },
  {
    id: "genre-15",
    title: "Chill",
    color: "#E8115B",
    cover: "/assets/genres/genre-15.jpeg",
    playlists: ["playlist-1", "playlist-2"],
  },
  {
    id: "genre-16",
    title: "Sleep",
    color: "#E91429",
    cover: "/assets/genres/genre-16.jpeg",
    playlists: ["playlist-1", "playlist-2"],
  },
  {
    id: "genre-17",
    title: "Party",
    color: "#056952",
    cover: "/assets/genres/genre-17.jpeg",
    playlists: ["playlist-1", "playlist-2"],
  },
  {
    id: "genre-18",
    title: "Romance",
    color: "#0C1D2D",
    cover: "/assets/genres/genre-18.jpeg",
    playlists: ["playlist-1", "playlist-2"],
  },
  {
    id: "genre-19",
    title: "Travel",
    color: "#A56752",
    cover: "/assets/genres/genre-19.jpeg",
    playlists: ["playlist-1", "playlist-2"],
  },
  {
    id: "genre-20",
    title: "Gaming",
    color: "#D84000",
    cover: "/assets/genres/genre-20.jpeg",
    playlists: ["playlist-1", "playlist-2"],
  },
];
export default GenreService;
