const SongServer = [
  {
    id: "song-1",
    title: "Early Rise",
    cover: "/assets/songs/song-1.jpeg",
    audio: "https://mp3.chillhop.com/serve.php/?mp3=10075",
    artists: ["artist-1", "artist-2", "artist-3"],
    categories: [""],
    isActive: false,
  },

  {
    id: "song-2",
    title: "Another day",
    cover: "/assets/songs/song-2.jpeg",
    audio: "https://mp3.chillhop.com/serve.php/?mp3=9272",
    artists: ["artist-4", "artist-5", "artist-6"],
    categories: [""],
    isActive: false,
  },
  {
    id: "song-3",
    title: "Bubble bath",
    cover: "/assets/songs/3.jpg",
    audio: "https://mp3.chillhop.com/serve.php/?mp3=9272",
    artists: ["artist-7", "artist-8", "artist-9"],
    categories: [""],
    isActive: false,
  },
  {
    id: "song-4",
    title: "Empty rooms",
    cover: "/assets/songs/4.jpg",
    audio: "https://mp3.chillhop.com/serve.php/?mp3=9272",
    artists: ["artist-10", "artist-11"],
    categories: [""],
    isActive: false,
  },
  {
    id: "song-5",
    title: "Every nights in",
    cover: "/assets/songs/5.jpg",
    audio: "https://mp3.chillhop.com/serve.php/?mp3=9272",
    artists: ["artist-2", "artist-4", "artist-6"],
    categories: [""],
    isActive: false,
  },
  {
    id: "song-6",
    title: "Roses along way",
    cover: "/assets/songs/6.jpg",
    audio: "https://mp3.chillhop.com/serve.php/?mp3=9272",
    artists: ["artist-1", "artist-3", "artist-6"],
    categories: [""],
    isActive: false,
  },
  {
    id: "song-7",
    title: "Just up",
    cover: "/assets/songs/7.jpg",
    audio: "https://mp3.chillhop.com/serve.php/?mp3=9272",
    artists: ["artist-2", "artist-7", , "artist-11"],
    categories: [""],
    isActive: false,
  },
  {
    id: "song-8",
    title: "Stromy night",
    cover: "/assets/songs/8.jpg",
    audio: "https://mp3.chillhop.com/serve.php/?mp3=9272",
    artists: ["artist-6", "artist-4", "artist-1"],
    categories: [""],
    isActive: false,
  },
  {
    id: "song-9",
    title: "Jab we met",
    cover: "/assets/songs/9.jpg",
    audio: "https://mp3.chillhop.com/serve.php/?mp3=9272",
    artists: ["artist-7", "artist-2", "artist-6"],
    categories: [""],
    isActive: false,
  },
  {
    id: "song-10",
    title: "Special person",
    cover: "/assets/songs/10.jpg",
    audio: "https://mp3.chillhop.com/serve.php/?mp3=9272",
    artists: ["artist-7", "artist-4", "artist-9"],
    categories: [""],
    isActive: false,
  },
  {
    id: "song-11",
    title: "Someone new",
    cover: "/assets/songs/11.jpeg",
    audio: "https://mp3.chillhop.com/serve.php/?mp3=9272",
    artists: ["artist-5", "artist-1"],
    categories: [""],
    isActive: false,
  },
  {
    id: "song-12",
    title: "Loveliest dream",
    cover: "/assets/songs/12.jpg",
    audio: "https://mp3.chillhop.com/serve.php/?mp3=9272",
    artists: ["artist-7", "artist-6"],
    categories: [""],
    isActive: false,
  },
  {
    id: "song-13",
    title: "The night you",
    cover: "/assets/songs/13.jpeg",
    audio: "https://mp3.chillhop.com/serve.php/?mp3=9272",
    artists: ["artist-1", "artist-11"],
    categories: [""],
    isActive: false,
  },
  {
    id: "song-14",
    title: "Swang song",
    cover: "/assets/songs/14.jpg",
    audio: "https://mp3.chillhop.com/serve.php/?mp3=9272",
    artists: ["artist-2", "artist-5", "artist-3"],
    categories: [""],
    isActive: false,
  },
  {
    id: "song-15",
    title: "We may sing",
    cover: "/assets/songs/15.webp",
    audio: "https://mp3.chillhop.com/serve.php/?mp3=9272",
    artists: ["artist-4", "artist-6", "artist-8"],
    categories: [""],
    isActive: false,
  },
  {
    id: "song-16",
    title: "Go fast",
    cover: "/assets/songs/16.jpg",
    audio: "https://mp3.chillhop.com/serve.php/?mp3=9272",
    artists: ["artist-5", "artist-7", "artist-6"],
    categories: [""],
    isActive: false,
  },
  {
    id: "song-17",
    title: "You are mine",
    cover: "/assets/songs/17.jpg",
    audio: "https://mp3.chillhop.com/serve.php/?mp3=9272",
    artists: ["artist-3", "artist-6", "artist-10"],
    categories: [""],
    isActive: false,
  },
  {
    id: "song-18",
    title: "Be tuned",
    cover: "/assets/songs/18.jpg",
    audio: "https://mp3.chillhop.com/serve.php/?mp3=9272",
    artists: ["artist-4", "artist-1"],
    categories: [""],
    isActive: false,
  },
  {
    id: "song-19",
    title: "The wonder morning",
    cover: "/assets/songs/19.png",
    audio: "https://mp3.chillhop.com/serve.php/?mp3=9272",
    artists: ["artist-1", "artist-2", "artist-3"],
    categories: [""],
    isActive: false,
  },
  {
    id: "song-20",
    title: "The night you came",
    cover: "/assets/songs/song-3.jpeg",
    audio: "https://mp3.chillhop.com/serve.php/?mp3=9272",
    artists: ["artist-4", "artist-5", "artist-6"],
    categories: [""],
    isActive: false,
  },
  {
    id: "song-21",
    title: "The mountain camel",
    cover: "/assets/songs/21.jpg",
    audio: "https://mp3.chillhop.com/serve.php/?mp3=9272",
    artists: ["artist-1", "artist-3", "artist-5"],
    categories: [""],
    isActive: false,
  },
  {
    id: "song-22",
    title: "A long story",
    cover: "/assets/songs/22.jpg",
    audio: "https://mp3.chillhop.com/serve.php/?mp3=9272",
    artists: ["artist-2", "artist-4", "artist-6"],
    categories: [""],
    isActive: false,
  },
  {
    id: "song-23",
    title: "Close up away",
    cover: "/assets/songs/23.jpeg",
    audio: "https://mp3.chillhop.com/serve.php/?mp3=9272",
    artists: ["artist-3", "artist-7"],
    categories: [""],
    isActive: false,
  },
  {
    id: "song-24",
    title: "Your adata",
    cover: "/assets/songs/24.jpg",
    audio: "https://mp3.chillhop.com/serve.php/?mp3=9272",
    artists: ["artist-5", "artist-6"],
    categories: [""],
    isActive: false,
  },
  {
    id: "song-25",
    title: "Essential winter",
    cover: "/assets/songs/25.jpg",
    audio: "https://mp3.chillhop.com/serve.php/?mp3=9272",
    artists: ["artist-1", "artist-2", "artist-7"],
    categories: [""],
    isActive: false,
  },
  {
    id: "song-26",
    title: "A nightmare wolf",
    cover: "/assets/songs/26.jpg",
    audio: "https://mp3.chillhop.com/serve.php/?mp3=9272",
    artists: ["artist-3", "artist-4", "artist-6"],
    categories: [""],
    isActive: false,
  },
  {
    id: "song-27",
    title: "Ek mulaqat",
    cover: "/assets/songs/27.jpg",
    audio: "https://mp3.chillhop.com/serve.php/?mp3=9272",
    artists: ["artist-2", "artist-5", "artist-7"],
    categories: [""],
    isActive: false,
  },
  {
    id: "song-28",
    title: "Your destiny short",
    cover: "/assets/songs/28.webp",
    audio: "https://mp3.chillhop.com/serve.php/?mp3=9272",
    artists: ["artist-1", "artist-3"],
    categories: [""],
    isActive: false,
  },
  {
    id: "song-29",
    title: "Before we leave",
    cover: "/assets/songs/29.jpg",
    audio: "https://mp3.chillhop.com/serve.php/?mp3=9272",
    artists: ["artist-2", "artist-5", "artist-6"],
    categories: [""],
    isActive: false,
  },
  {
    id: "song-30",
    title: "Curse your day",
    cover: "/assets/songs/30.jpeg",
    audio: "https://mp3.chillhop.com/serve.php/?mp3=9272",
    artists: ["artist-5", "artist-6", "artist-7"],
    categories: [""],
    isActive: false,
  },
  {
    id: "song-31",
    title: "Lofi hip hop",
    cover: "/assets/songs/1.jpg",
    audio: "https://mp3.chillhop.com/serve.php/?mp3=9272",
    artists: ["artist-1", "artist-6", "artist-7"],
    categories: [""],
    isActive: false,
  },
  {
    id: "song-32",
    title: "I will be",
    cover: "/assets/songs/2.jpg",
    audio: "https://mp3.chillhop.com/serve.php/?mp3=9272",
    artists: ["artist-2", "artist-4", "artist-7"],
    categories: [""],
    isActive: false,
  },
];
export default SongServer;
